spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nbcamp?useUnicode=true&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 0
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
